In [3]:
import pandas as pd
results = pd.read_csv('tmp/1.38037-PB1-9531-R2.pdf.tika.cleaned.csv',index_col=0)
results

,Paragraph ID,Sentence ID,Score,Sentence
0,0,0,62.430725,Page 1 of 14
1,1,0,23.342031,© Annals of Translational Medicine
2,1,1,73.067440,All rights reserved
3,1,2,91.083260,Ann Transl Med 2020;8(6):299 | http://dx
4,1,3,NaN,doi
...,...,...,...,...
3262,2295,3,6.095510,doi: 10
3263,2295,4,1498.973300,21037/ atm
3264,2295,5,NaN,2020
3265,2295,6,NaN,02
3266,2295,7,NaN,175

In [4]:
good_results = results[results['Score']<=300]
good_results

,Paragraph ID,Sentence ID,Score,Sentence
0,0,0,62.430725,Page 1 of 14
1,1,0,23.342031,© Annals of Translational Medicine
2,1,1,73.067440,All rights reserved
3,1,2,91.083260,Ann Transl Med 2020;8(6):299 | http://dx
5,1,4,210.339920,org/10
...,...,...,...,...
3258,2294,3,166.065280,Pract Res Clin Rheumatol 2014;28:377-93
3259,2295,0,52.516820,"Cite this article as: Wu A, March L, Zheng X, ..."
3260,2295,1,61.296730,Global low back pain prevalence and years live...
3261,2295,2,87.012690,Ann Transl Med 2020;8(6):299
3262,2295,3,6.095510,doi: 10

In [23]:
good_paragraphs = good_results.groupby('Paragraph ID').apply(lambda x: ".".join(x['Sentence']))
good_paragraphs = good_paragraphs[good_paragraphs.str.len() > 50] # min num characters
good_paragraphs

Paragraph ID
1       © Annals of Translational Medicine.All rights ...
2       Global low back pain prevalence and years live...
3       Aimin Wu1, Lyn March2,3, Xuanqi Zheng1, Jinfen...
4       1Division of Spine Surgery, Department of Orth...
5       Hospital of Wenzhou Medical University, Zhejia...
                              ...
2291    The epidemiology of low back pain in the rest ...
2292    Shiri R, FalahHassani K, Heliovaara M, et al.R...
2293    Vlaeyen JWS, Maher CG, Wiech K, et al.Low back...
2294    Hoy D, Geere JA, Davatchi F, et al.A time for ...
2295    Cite this article as: Wu A, March L, Zheng X, ...
Length: 132, dtype: object

In [30]:
i = 0
for p in good_paragraphs:
    print(i,len(p))
    open(f"tmp/content_{i}.txt","w").write(str(p))
    i+=1

0 102
1 137
2 150
3 139
4 137
5 135
6 130
7 130
8 139
9 138
10 129
11 91
12 139
13 138
14 139
15 56
16 134
17 1454
18 99
19 58
20 102
21 289
22 666
23 643
24 543
25 68
26 238
27 521
28 219
29 231
30 51
31 200
32 399
33 169
34 69
35 102
36 130
37 119
38 417
39 83
40 136
41 371
42 201
43 433
44 52
45 102
46 100
47 54
48 69
49 102
50 54
51 159
52 102
53 226
54 145
55 69
56 102
57 102
58 69
59 102
60 102
61 538
62 232
63 51
64 455
65 56
66 255
67 70
68 102
69 680
70 799
71 569
72 502
73 378
74 393
75 574
76 1076
77 102
78 692
79 325
80 1265
81 188
82 654
83 553
84 625
85 155
86 70
87 102
88 198
89 75
90 439
91 509
92 122
93 133
94 83
95 101
96 179
97 109
98 176
99 153
100 98
101 98
102 122
103 178
104 192
105 243
106 301
107 222
108 116
109 164
110 102
111 152
112 189
113 98
114 155
115 130
116 201
117 99
118 91
119 133
120 158
121 96
122 181
123 167
124 165
125 120
126 134
127 150
128 156
129 51
130 222
131 284

In [28]:
p

'© Annals of Translational Medicine.All rights reserved.Ann Transl Med 2020;8(6):299 | http://dx.org/10'

28616